### ISSUE TITLE
Aside block with images

### ISSUE THREAD

**Issue by troychaplin** [ravendesignsystem/rds#66]
I'm confused as to why images in aside blocks are forcing max-heights at 2 different breakpoints? I didn't see anything mentioned in the documentation on requirements or restrictions for images, but before i clean up that stuff, I wanted to ask if there was a reason why we are doing this?

https://ravendesignsystem.github.io/rds/dev/blocks/aside/sidebar/

This is the block of CSS that I was looking to change:

```css
.b-sidebar > h2 + img {
	object-fit: cover;
	width: 100%;
	margin-bottom: 20px;
	max-height: 232px;

	+ p {
		padding-top: 0;
	}

	@include media('>=l') {
		max-height: 160px;
	}
}
```

This is what I want to change it to, unless there's a reason we are restricting it (which then should be mentioned in documentation page):

```css
.b-sidebar > h2 + img {
	width: 100%;
	height: auto;
	margin-bottom: 20px;

	+ p {
		padding-top: 0;
	}
}
```
